### ISSUE TITLE
Does it support automatic transition across all routes?

### ISSUE THREAD

**Issue by rnarayan** [ccorcos/meteor-transitioner#1]
Great package that was needed by the community. Thanks of making it. 
If someone wanted the transition across all the routes in an app, would the team have to define every possible combination of routes in the Transitioner.transition({ }). It will be helpful to have an option where the transition takes place for every route change.

Also, how does it handle waitOn in ironrouter. Does the transition start immediately or wait for waitOn. Thanks in advance for your answers.

**Comment by ccorcos** [comment]
There is support a default animation but I haven't supported it yet. This will go on the TODO list.

https://github.com/ccorcos/meteor-transitioner/blob/master/lib/transitioner.coffee#L29

I haven't done any testing with `waitOn`. This will likely be a problem if Iron router renders the loading template in between routes... Any ideas how to fix this?

**Comment by etmarch** [comment]
+1 for the default routes. I have over 30 routes defined, so there are a tremendous amount of different route pairs that can be formed in my app.

**Comment by ccorcos** [comment]
Should be working now

**Comment by etmarch** [comment]
Sorry to reply again, but is there any chance you could show a small snippet of code for setting a default transition? I'm not exactly sure how to go about that.

**Comment by etmarch** [comment]
In the meantime I got this code working decently well for me. I have all my routes in an array so its pretty self explanatory, since I really only care for one style of animation.

```
for (var i = 0; i < privateRoutes.length; i++ ) {

        for (var j = 0; j < privateRoutes.length; j++) { // each
            Transitioner.transition({
                fromRoute: privateRoutes[i],
                toRoute: privateRoutes[j],
                velocityAnimaton: {
                    "in": 'transition.slideRightBigIn',
                    out: 'transition.slideLeftBigOut'
                }
            });
        }

    }
```

**Comment by ccorcos** [comment]
```
Transitioner.default
  in: 'transition.fadeIn'
  out: 'transition.fadeOut'
```

I just added it to the readme.

**Comment by etmarch** [comment]
Haha I guess I should have waited 7 minutes, but thank you very much.
