### ISSUE TITLE
DOM there, but yield area hidden

### ISSUE THREAD

**Issue by Digital-Thor** [ccorcos/meteor-transitioner#12]
Hi Chet, great idea for a package.  Thanks!  

I got it working, but had to hack around a bit. Basically, my yield areas were still in the DOM and routing, but hidden.  When I used the Chrome web inspector to check:

`<div class="transitioner" id="transitioner-0">my HTML</div>`

I found the CSS was set to:

```
.transitioner {
    height: 100%;
    width: 100%;
    overflow: hidden;
    position: relative;
}
```

So I added a CSS rule `.transitioner {  overflow:visible }`.  After that change, yield areas became visible and transitions worked properly. Any thoughts on why `overflow` would be hidden?

**Comment by ccorcos** [comment]
Well its assumed that everything inside the transitioner is full sized. Anything larger could cause it to scroll which would be odd. I suppose it doesn't really matter though. If it works for you then rock on!
