### ISSUE TITLE
Template in transitioner not renderring

### ISSUE THREAD

**Issue by Kendaii** [ccorcos/meteor-transitioner#13]
Hi,

I try to use the meteor-transitioner package but each time i try to change page, the transition animation is played but the template of the destination page never render.

For more details, I ask a question on stackovferflow here : http://stackoverflow.com/questions/31154324/meteor-template-not-rendering-with-slide-transition

**Comment by ccorcos** [comment]
Can you recreate this issue in a Meteorpad?  You seem to be doing things right...

**Comment by ccorcos** [comment]
Also, maybe a long shot -- try using the `{display: null}` option in your animation.

**Comment by Kendaii** [comment]
I try to recreate the issue on a Meteorpad but it seems to be working perfectly : http://meteorpad.com/pad/GNFHMZaBckECXqPGP/TransitionTest

The `{display: null}` option should be on the transition or in the animation definition like this ?

```
$.Velocity.RegisterEffect('transition.pushRightIn',
{
  defaultDuration: 1500,
  display: null,
  calls: [
    [ { translateX: ['0%', '100%'], translateZ: 0, easing: "ease-in-out", opacity: [1, 1] } ]
]});
```

**Comment by ccorcos** [comment]
From the Velocity's docs:

> Elements automatically switch to display: block/inline when transitioning in, and back to display: none after transitioning out. (To prevent this behavior, pass display: null as an option into the UI Pack call.)

So you want to try `$elem.velocity('myAnimation', {display:null})`.

**Comment by ccorcos** [comment]
If you can't recreate the issue, I'm afraid I won't be able to help. You're saying it doesnt render at all?

**Comment by Kendaii** [comment]
On destination page, there is the `<div id="transitioner-0" class="transitioner"></div>` but nothing inside. 
If I refreshed the page, the template render normally as

```
<div id="transitioner-0" class="transitioner">
   <nav>...</nav>
   <div class="page">...</div>
</div>
```

**Comment by ccorcos** [comment]
Hmm. So I'm using `_uihooks`.

https://github.com/ccorcos/meteor-transitioner/blob/master/lib/transitioner.coffee#L86

Any it must not be firing. Maybe you're changing the layout or something and the transitioner is being rerendered? You're definitely doing something here that you're not telling me about...

**Comment by Kendaii** [comment]
Actually, I may misunderstood the issue here. The template is rendered, because I can see `console.log()` message placed into the `Template.about_page.onRendered(function() { })`. 
Anyway, the template is not inserted into the DOM. 

I really searched what I've been doing that can occur the error but I really don't know.

**Comment by ccorcos** [comment]
try cloning this repo into your projects `/packages` directory and adding some console.log statements inside the _uihooks, specifically the added one. Somehow its not being inserted into the DOM. Or perhaps you're doing some redirecting in the router which is causing it to be rendered and then removed very quickly or something...

**Comment by Kendaii** [comment]
Okay, inside the `insertElement` it seems that the `next` variable is always null. So the `return $(node).insertBefore(next).velocity(animation["in"]);` try to insert the template before a null element...

Doing something like `return $(_ref).append(node).velocity(animation["in"]);` works. But, I can have only one template or I get the animation played several times.

**Comment by ccorcos** [comment]
Hmm. So what if you put a dummy <div> right after the transitioner? Then it shouldnt be null right?

**Comment by Kendaii** [comment]
Everything works perfectly now, thank you very much for your help ! ;)
