### ISSUE TITLE
Total malfunction

### ISSUE THREAD

**Issue by ffxsam** [ccorcos/meteor-transitioner#15]
The CSS is doing some strange stuff:

https://github.com/ccorcos/meteor-transitioner/blob/master/lib/transitioner.css#L8

I noticed it was totally messing up my div, so I placed a container around `{{> yield}}` like so:

```
{{#transitioner}}
  <div>
    {{> yield}}
  </div>
{{/transitioner}}
```

But this didn't help. Not I have a totally blank page for some reason (except for the stuff outside the `{{#transitioner}}` block). Not sure how to troubleshoot this.

**Comment by ccorcos** [comment]
Check out the example. Each view must be self-contained within an absolute positioned div.

**Comment by ffxsam** [comment]
So your CSS makes the first child div absolute position, looks like. But still, it doesn't work with the site I'm working on. I followed the instructions in the README exactly, and it fails. Are there any known incompatibilities with Bootstrap? Or anything?

**Comment by ccorcos** [comment]
can you describe this failure?

**Comment by ffxsam** [comment]
Let me put together some code when I get some time, and I'll send you a link to the repo.

**Comment by ccorcos** [comment]
ok. preferably a minimal reproduction in a meteorpad

**Comment by markshust** [comment]
Same here... the transition fires, then loads the new template. Then everything under .transitioner in the DOM is gone.

**Comment by markshust** [comment]
Also wanted to note, the exact same thing is happening to me with https://atmospherejs.com/jamielob/transitions -- perhaps something changed with a recent version of something. The url path changes, however the DOM is blank under the transition container.

**Comment by ccorcos** [comment]
honestly, I don't know what to tell you without and example I can look at. Is your project on github?

**Comment by markshust** [comment]
I created a test Meteorpad, and everything looks good: http://meteorpad.com/pad/sPcneDtSDWrDbcHWu/Transition

I'm going to re-test with my current app to find out if possibly another module is causing this, if there is another issue, or if I'm just an idiot.

**Comment by ffxsam** [comment]
I haven't had time to come back to this. But I'll probably wind up not using it since I plan on moving away from Iron Router and start using Flow Router.

**Comment by ccorcos** [comment]
haha. yeah I've moved on to a more simple router -- `ccorcos:client-router`. I'll reopen this issue if you can demonstrate the problem

**Comment by markshust** [comment]
i believe i've found the issue -- stems back to jade https://github.com/jamielob/transitions/issues/11
