### ISSUE TITLE
Is this package used for swipe gestures in mobile

### ISSUE THREAD

**Issue by avishekgurung** [ccorcos/meteor-transitioner#16]
Hi,

Could be a amateur question. But I wanna know if this package can be used for a swipe gestures in mobile?

The requirements would be like

on swipe-left -> router should hit -> deliver destination template

**Comment by ccorcos** [comment]
You can do that with hammer.js. But if you actually want to be able to swipe and drag, then check out this package:

https://github.com/ccorcos/meteor-swipe

I haven't worked on it in a while though. I'd highly recommend using it as a starting point but building another version using observable streams to abstract away all the internal state.

**Comment by avishekgurung** [comment]
But this transitioner package does not do that rite?

**Comment by ccorcos** [comment]
This package does not.
