### ISSUE TITLE
Detecting Back Button?

### ISSUE THREAD

**Issue by evolross** [ccorcos/meteor-transitioner#19]
Is there a way to detect a Back button press and call a different transition?  

I get that I could try to map out specific transitions between routes and because of my app design hitting the back button will look "right" in some cases because it will be the logical back route to the current route.  

For example, if most of my app transitions with a "slideRight" look, it would be nice to always do a "slideLeft" when Back is pushed so it appears to be going backward.

**Comment by nicooprat** [comment]
+1

I tried some hacks to do so, but no success... it's pretty hard. The idea is to listen to the `popstate` event and try to check if the new URL is the same as the `history - 2`, and so guess that the user clicked the back button.

Too bad there's no standard for this !

**Comment by evolross** [comment]
I think this is why most apps that you see have a "Back" button or some kind of button in the upper left corner that you can control the transition on.  Because the real "back" button is an issue.

**Comment by ccorcos** [comment]
This package works by detecting the url change through iron router. The back button works so long as you set up the inverse animation on the reverse url change. Check out the example!

http://ccorcos-transitioner.meteor.com/

**Comment by nicooprat** [comment]
Yes I saw that your package is the only one that manage back and forth transitions, but having to manually indicates each case is a bit fastidious.

**Comment by ccorcos** [comment]
well this package is just meant to be as general as possible. it should be trivial to great your own abstraction around the API to do specifically what you want very cleanly.

**Comment by nicooprat** [comment]
Yes sure, I'm pretty new to Meteor. We're a bit out of the initial subject, but actually I'm trying to "merge" Meteor with [Framework7](http://www.idangero.us/framework7/). That's how I arrived here, looking for a way to hook routing/templating of Meteor to use Framework7 transitions (and so back buttons too).

**Comment by ccorcos** [comment]
hmm. does framework7 support infinitely nested tabs and navs? because a typical tab-nav layout cant work with the linear browser history. for my apps, i actually maintain a histroy internally so back will go back in that particular tabs nav history...

**Comment by nicooprat** [comment]
What do you mean by "infinitely nested" ? F7 seems first meant for hybrid apps, with an option "pushState" (disabled by default) to manage URLs in web browsers — so I guess it should be working pretty much like a native app. I know it supports (multiple) views, tabs, navbars and history with swipe-back feature (à la iOS) for example.

You're right, browsers have only one URL at a time, so I'll need to restrict myself toandthink my app in this way, so it can work on native and web. But that's a theoretical issue, I'm currently struggling with a more technical one :)

Anyway, thanks for your help !

**Comment by ccorcos** [comment]
> What do you mean by "infinitely nested" ?

Think about the Instagram app. There are multiple tabs with separate navigation stacks. Suppose you navigate 10 pages deep on tab ONE, then switch to tab TWO and navigate 5 pages deep on there. Then you switch back to tab ONE again. When you press back in the browser, it shouldn't take you back to tab TWO. Its should pop off a view from the navigation stack specific to that tab. For that reason, using a linear browser history isn't practical for modern apps.

**Comment by nicooprat** [comment]
Ok, got it. Yes, Framework7 looks built to behave like this. Actually I think it's its default usage, there's only an option called `pushState` that change URL when going from page to page. Framework7 supports multiple views with each unique history, and even multiple views in same viewport (for example : http://www.idangero.us/framework7/examples/split-view-panel/).

So, in the default configuration, there's no "real" back button like in a browser : you either click on the view's back button, on swipe back in this view (don't know what would happen with Android back button though), so it's easy to know which view has to go back.

Anyway, I agree that native-behavior and web-accessibility are hard to merge :) Iframes to the rescue ? Just kidding... or am I ?

**Comment by ccorcos** [comment]
idk. I'm leaning more and more away from accessibility. some apps certainly benefit from accessibility. But other apps I think should be written in straight OpenGL. Accessibility features should just be an api for these apps. But this gives you optimal performance and less hacking on weird HTML/CSS/JS quirks.

**Comment by ccorcos** [comment]
Anyways, I'm going to close this. The back button works with transitions...
