### ISSUE TITLE
transitioner css overflow property displays nothing for the yield

### ISSUE THREAD

**Issue by etmarch** [ccorcos/meteor-transitioner#2]
Great package so far, thank you very much. 

I am having one strange issue though - When I wrap my yield call in the transitioner div, no content displays at all, unless I override the overflow:hidden css rule with overflow:initial in my css. Everything else works perfectly fine though. Any ideas what this could be?

**Comment by ccorcos** [comment]
I'm not sure what you're talking about. Why is there overflow:hidden? That would seem to explain things not showing up to me... ;)

**Comment by etmarch** [comment]
It must have been some sort of conflict with my particular environment I guess, but either way, I just simply set it to initial, and now its fine. I tip my hat to you sir, its crazy how fast my meteor app started looking/feeling like a real SPA.

**Comment by ccorcos** [comment]
haha thanks man
