### ISSUE TITLE
Doesn't work with materializecss

### ISSUE THREAD

**Issue by ghost** [ccorcos/meteor-transitioner#20]
Install materializecss -> not working transitioner. Is there any idea?..

**Comment by ghost** [comment]
Well, if in the .meteor/packages we put the materialize:materialize string <b>before</b> the ccorcos:transitioner string, transitions work again. So, materializecss must be loaded before the ccorcos:transitioner.

**Comment by bkuri** [comment]
@django43ru this did not work for me. I have `materialize:materialize` near the beginning of my `packages` file and `ccorcos:transitioner` at the very end.

I do notice that the "out" transition does fire sometimes, but the "in" one doesn't. After the first transition finishes, the html looks like this:

```
<div id="transitioner-0" class="transitioner"></div>
```

**Comment by ghost** [comment]
There is an issue with materializecss 0.97.1 version. Try this:

//in .meteor/packages
...
materialize:materialize**@0.97.0**

//in .meteor/versions
...
materialize:materialize**@0.97.0**

Don't forget to correct the version of materialize in versions-file **after** loading the package. I hope, that will help you.
