### ISSUE TITLE
Scroll does not work on states with different height

### ISSUE THREAD

**Issue by dani-z** [ccorcos/meteor-transitioner#22]
Hi,

Thank you for the awesome plugin! At the moment I am building the UI for a mobile app and I am using this plugin. Everything works just fine, except the fact that, when going from a screen to another, I can't use the scroll anymore (screen height vary). I tried to debug the CSS but no luck so far.

Any advice you may have on this?

Regards,

**Comment by ccorcos** [comment]
you need to use absolute positioning for your views with overflow-scroll. This is the only way you can transition properly.
