### ISSUE TITLE
In and Out content both present during transition

### ISSUE THREAD

**Issue by n8barr** [ccorcos/meteor-transitioner#26]
I followed your example, but I am seeing the incoming content show up below my exiting content during the transition. I am using multiple named > yield elements in my layout, which seems to be different than your implementation. Does your package not support that? Or is there another implementation step that I am likely missing?

**Comment by ccorcos** [comment]
I'm not sure it does. Check out the source code. This transitioner works only in a very specific way, but you can just check out how its build and do the same thing yourself!
