### ISSUE TITLE
Is there a way to attach a transition to moveelement?

### ISSUE THREAD

**Issue by advany** [ccorcos/meteor-transitioner#5]
out and in works great but move is not working. I was trying to see how to fit it in myself but couldn't figure it out

**Comment by ccorcos** [comment]
move is very challenging. it would probably be more suitable for this package:

https://github.com/ccorcos/meteor-animate

but anyways, you've got to register to the _uihook moveElement which [give you the node and the next node](https://github.com/ccorcos/meteor-blaze-animations/blob/master/client/main.coffee#L64). I tried messing with it once, but its really hard to transition your entire UI accordingly. Feel free to give it a shot though! I'm sure its possible (but not with this transitioner package ;)

**Comment by ccorcos** [comment]
check this out for an example

https://github.com/DiscoverMeteor/Microscope/commit/bd12a26748bfb45de5f98ba009f7be8312bee00f
